### ISSUE TITLE
Duplicating blocks with scrolltrigger animation and sliding them up on the page makes them hidden

### ISSUE THREAD

**Issue by covertnine** [covertnine/c9-animation#1]
My guess is the attributes are copied for the page position, so when I duplicate and move them up in the DOM, the new position is screwing with the animation scrolltriggers cause I've moved the blocks up a bit.

See below video.

https://recordit.co/zdOXJFUxP4

**Comment by dskrepps** [comment]
Didn't have to do with duplicating, just movement in general. The problem was keyframe trigger positions weren't updating any time a block's vertical position was moved so it needed ScrollTrigger.refresh(). Took a bit to figure out how to detect changes in the block editor but looks like I ended up with the only good solution to do so.
